### ISSUE TITLE
Update healthcheck.sh as `rabbitmqctl node_health_check` is deprecated

### ISSUE THREAD

**Issue by alemorcuq** [bitnami/bitnami-docker-rabbitmq#122]
**Description**
The `healthcheck.sh` script uses `rabbitmqctl node_health_check` to perform the healthcheck. However, this command and it's API counterpart have been deprecated. See:

```
$ rabbitmqctl node_health_check
This command is DEPRECATED and will be removed in a future version.
It performs intrusive, opinionated health checks and requires a fully booted node.
Use one of the options covered in https://www.rabbitmq.com/monitoring.html#health-checks instead.
Timeout: 70 seconds ...
Checking health of node rabbit@localhost ...
Health check passed
```

And in the logs:

```
2020-06-23 11:38:54.583 [warning] <0.1355.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
```

Please, update the script to use one of the [recommended approaches to health checking](https://www.rabbitmq.com/monitoring.html#health-checks).

**Comment by vermaabhay** [comment]
I think "rabbitmq-diagnostics -q check_port_connectivity" should be sufficient for checking node health as liveliness and readiness probe in K8s. 

RabbitMQ team discourages using "rabbitmqctl node_health_check". As "rabbitmqctl node_health_check" requires a fully booted node so if a node is waiting for a peer to appear to sync tables from, it cannot succeed and eventually enters into a node restart deadlock. Also, management health check doesn't work correctly on a heavily loaded node.

**Comment by javsalgar** [comment]
Thanks for the input! We will consider this when implemeting the feature

**Comment by possani** [comment]
Hey guys, any updates?

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. I will forward this message to see if we can re-prioritize

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
