### ISSUE TITLE
Image compliance issue due to example private keys from erlang package

### ISSUE THREAD

**Issue by agarwva2** [bitnami/bitnami-docker-rabbitmq#140]
@beltran-rubo - We are also running into compliance issue related to existence of private keys in the image, do you know if there is any ETA to get these example private keys removed from the image.
![image](https://user-images.githubusercontent.com/26313523/97920952-86289200-1d5a-11eb-9bbb-21088c91f8bd.png)

![image](https://user-images.githubusercontent.com/26313523/97920767-38ac2500-1d5a-11eb-8778-c96c652981f8.png)

_Originally posted by @agarwva2 in https://github.com/bitnami/bitnami-docker-rabbitmq/issues/127#issuecomment-720734202_

**Comment by FraPazGal** [comment]
Hi @agarwva2,

As my colleague told you, we have created an internal task which is planned to be worked on in the next couple of weeks. We will update this issue as soon as we have any more news!

**Comment by agarwva2** [comment]
thanks @FraPazGal for the feedback

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
