### ISSUE TITLE
CrashLoopBackOff because PermissionDenied

### ISSUE THREAD

**Issue by chaimfn** [bitnami/bitnami-docker-rabbitmq#160]
**Description**

Deployment of bitnami/rabbitmq:3.8.12 has been crashed, because a PermissionDenied error.

**Describe the results you received:**

Here is the whole log:
```
rabbitmq 23:57:02.45 Welcome to the Bitnami rabbitmq container
rabbitmq 23:57:02.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 23:57:02.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 23:57:02.47
rabbitmq 23:57:02.47 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 23:57:02.55 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 23:57:02.63 INFO  ==> Initializing RabbitMQ...
/opt/bitnami/scripts/librabbitmq.sh: line 375: /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf: Permission denied
```
**Additional environment details:**

I use tkgi cluster

**Comment by carrodher** [comment]
Unfortunately, I am not able to reproduce the issue by using the _docker-compose.yaml_ present in the root of this repository. I downloaded this file and modified the image to use the specific tag you're using:
```diff
services:
  rabbitmq:
-   image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
+   image: 'docker.io/bitnami/rabbitmq:3.8.12'
    ports:
      - '4369:4369'
      - '5672:5672'
```

Then deploying the above _docker-compose.yaml_ everything is working as expected:
```console
$ docker-compose up
rabbitmq_1  | rabbitmq 07:53:02.78 Welcome to the Bitnami rabbitmq container
rabbitmq_1  | rabbitmq 07:53:02.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq_1  | rabbitmq 07:53:02.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq_1  | rabbitmq 07:53:02.78
rabbitmq_1  | rabbitmq 07:53:02.79 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq_1  | rabbitmq 07:53:02.80 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq_1  | rabbitmq 07:53:02.81 INFO  ==> Initializing RabbitMQ...
rabbitmq_1  | rabbitmq 07:53:02.82 INFO  ==> Generating random cookie
rabbitmq_1  | rabbitmq 07:53:02.83 INFO  ==> Starting RabbitMQ in background...
rabbitmq_1  | rabbitmq 07:53:11.94 INFO  ==> Stopping RabbitMQ...
rabbitmq_1  | rabbitmq 07:53:15.11 INFO  ==> ** RabbitMQ setup finished! **
rabbitmq_1  | rabbitmq 07:53:15.12 INFO  ==> ** Starting RabbitMQ **
rabbitmq_1  |  Starting RabbitMQ 3.8.12 on Erlang 22.3
rabbitmq_1  |  Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
rabbitmq_1  |  Licensed under the MPL 2.0. Website: https://rabbitmq.com
rabbitmq_1  |
rabbitmq_1  |   ##  ##      RabbitMQ 3.8.12
rabbitmq_1  |   ##  ##
rabbitmq_1  |   ##########  Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
rabbitmq_1  |   ######  ##
rabbitmq_1  |   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
```

In order to reproduce the issue on our side, what is the deployment method you are using? Can you provide us the commands or customizations you are using?

This kind of permission issues sounds like you are mounting a folder/file from your local machine into the container without the proper permissions, please take into account when you mount something into the container, the permissions of the local folder are applied inside the container so you should modify the local permissions. In this case, as this is a non-root container, the mounted files and directories must have the proper permissions for the UID `1001`.

**Comment by chaimfn** [comment]
Hi.
I'm deploying on kubernetes, by using bitnami helm-chart.
After deployment, the status is CrashLoopBackOff (instead of Running) and the log above I get by 'kubectl logs <pod-name>'.

**Comment by carrodher** [comment]
In that case, it seems you need to enable the init container bundled in the Helm chart to properly set the permissions of the volume, see https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#adjust-permissions-of-the-persistence-volume-mountpoint and https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#volume-permissions-parameters
