### ISSUE TITLE
Is it possible to create a rabbitmq cluster in diffternt vms?

### ISSUE THREAD

**Issue by thangazm** [bitnami/bitnami-docker-rabbitmq#173]
I would like to know if we can create a rabbitmq cluster using different vms, fro example
vm 1 : rabbitmq 1
vm 2: rabbitmq 2
vm 3: rabbitmq 3

If so how we can connect the cluster?

**Comment by miguelaeh** [comment]
Hi @thangazm ,
If you want to do that using docker-compose you can do it by mapping the ports to the VM.
Could you provide more information on how would you like to do it?

**Comment by thangazm** [comment]
Yes, I will explain how I want to do it.

I have 3 virtual machines. I need to run one rabbitmq containers per machine. So that leads up to 3 vm's and 1 container per each vm.

For example,

vm 1,
ip: 10.10.10.1
rabbitmq-1 (this means 1 rabbitmq bitnami container)

vm 2,
ip: 10.10.10.2
rabbitmq-2

vm 3,
ip: 10.10.10.2
rabbitmq-3

As you can see now we have 3 rabbitmq nodes running in 3 virtual machines. Now I want to configure these 3 nodes to rabbitmq cluster talking to each other. 

How can I do that?

**Comment by miguelaeh** [comment]
Hi @thangazm ,

If I understood it properly, you want to set an IP address in the second part of the `RABBITMQ_CLUSTER_NODE_NAME` instead of a hostname.
I am afraid that is not possible by the RabbiMQ design as explained here: https://www.rabbitmq.com/clustering.html#hostname-resolution-requirement

If you don't have DNS for those VMs, you can try by editing the `/etc/hosts` files manually or any of the methods explained in the above link.

**Comment by thangazm** [comment]
Thank you @miguelaeh this is helpful.
