### ISSUE TITLE
Can we have two stats node in a cluster?

### ISSUE THREAD

**Issue by thangazm** [bitnami/bitnami-docker-rabbitmq#188]
I need to have 2 stats nodes to allow the management UI to be accessed because I want to create HA for UI, As it seems when I have 2 stats node one stat node cant join to a cluster, what are the possible solution for this

**Comment by carrodher** [comment]
I'm not sure if we can help you with this topic since it seems it is not an issue related to the Bitnami Rabbitmq container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
