### ISSUE TITLE
Document how to test patches against rabbitmq source code

### ISSUE THREAD

**Issue by horazont** [bitnami/bitnami-docker-rabbitmq#199]
### Name and Version

any

### What is the problem this feature will solve?

When investigating a rabbitmq issue and working with upstream to resolve it, it is useful to be able to build custom images which have various patches applied.

This image downloads an opaque tarball from download.bitnami.com, which seems to contain the compiled rabbitmq server. It is thus not easy to patch.

### What is the feature you are proposing to solve the problem?

Documentation should be added on how to build such a tarball in order to be able to apply patches to the rabbitmq source code or build process and inject that into the image.

### What alternatives have you considered?

Switching to library/rabbitmq as a base image, potentially porting some of the scripts from this repository. This would be extra work for us which may be avoidable if the build process is documented somewhere.

**Comment by rafariossaa** [comment]
Hi,
  As you indicated, the tar ball is the result of the compilation in our internal CI/CD pipelines. It takes the standard compilation steps and creates the tar ball. I can not share it because it would make more sense because it is tied to our internal processes and tools.
  If you want to replace the binaries, you could create a similar tarball and replace the step in the docker file.
