### ISSUE TITLE
Image fails when used with Kubernetes and EFS

### ISSUE THREAD

**Issue by faraazkhan** [bitnami/bitnami-docker-rabbitmq#54]
For details see issue in the helm repo: https://github.com/kubernetes/charts/issues/1711

**Comment by RichiCoder1** [comment]
Can confirm this appears to still be the case

**Comment by clintmod** [comment]
This is preventing me from using the bitnami rabbitmq image in prod because it takes the container 10-20 minutes to boot up in prod when I mount the /bitnami folder to an efs share.

**Comment by clintmod** [comment]
Can someone correct me if I'm wrong in my view here but…  it seems like this image is geared more toward HA.  And if I'm running rabbit in HA we don't need to have an efs/nfs volume. If I don't want HA I can just use the official rabbit image (https://hub.docker.com/_/rabbitmq) backed with efs.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
