### ISSUE TITLE
memory watermark is not supported

### ISSUE THREAD

**Issue by redbaron** [bitnami/bitnami-docker-rabbitmq#68]
Currently there is not way to run bitnami rabbitmq image in memory-limited containers. There is no way to have `vm_memory_high_watermark` value set  in  rabbitmq.conf

**Comment by juan131** [comment]
I'm not sure if we are going to provide a way to configure via env. variable every configuration parameter on **rabbitmq.conf**. As an alternative, you can edit the [init scripts](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.7/rootfs/app-entrypoint.sh) so you edit the configuration file with your custom parameters after initialising RabbitMQ.

**Comment by redbaron** [comment]
1. config format for rabbitmq is not very bash friendly
2. limiting memory of a container is a very common setup, supporting it is a bare minimum and almost every use of this image would want to do it at some point. unfortunately /proc/meminfo which most apps use to determine available memory is showing host values, so wrong defaults are picked up by most software.
3. official docker image (which I ended up using) supports it out of the box and stresses it as much as it can in its readme importance of this parameter

**Comment by juan131** [comment]
@tompizmor @jotadrilo any thoughts about adding this parameter to the available configuration options?

**Comment by jotadrilo** [comment]
I think we could explore the possibility of using the `advanced.config` file for this, so users can set advanced or custom configuration and mount it separately.

This is just a proposal, though. We should also evaluate if it is worth to expose this specific setting. cc. @tompizmor

**Comment by tompizmor** [comment]
I think in this specific case it is worth it to expose this setting as the official docker image does

**Comment by juan131** [comment]
We have created a task to add this setting and it has been included it in our backlog. It will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
