### ISSUE TITLE
Configuring enabled_plugins on cluster nodes (docker-compose.yml)

### ISSUE THREAD

**Issue by xtender** [bitnami/bitnami-docker-rabbitmq#73]
What is the easiest way to enable, for example, rabbitmq_stomp?
Also I see that management plugin is enabled on the first node only (where RABBITMQ_CLUSTER_NODE_NAME is not set).

**Comment by juan131** [comment]
@tompizmor could you please share your thoughts? It shouldn't be a dramatic change in the logic.

**Comment by tompizmor** [comment]
I agree! We could have an env var to specify the plugins to install. AFAIK, this feature is already available in the helm chart. https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L69-L71

**Comment by juan131** [comment]
Cool! I created a task to implement a solution similar to ElasticSearch one. 

This way the user doesn't need to mount the binaries since they'll be installed during the initialisation. The current solution in the chart just enables it in the configuration file!

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
