### ISSUE TITLE
Upgrade Erlang to 21.1.2

### ISSUE THREAD

**Issue by juhtie01** [bitnami/bitnami-docker-rabbitmq#83]
**Description**

FEATURE REQUEST: Please upgrade Erlang to version 21.1.2 in the images.

We seem to be hitting a TLS bug which is present in Erlang version 21.1.0 described in https://groups.google.com/forum/?nomobile=true#!topic/rabbitmq-users/sDe1AueOgZo. Our RabbitMQ processes randomly crash with seemingly no indication on what happens. It seems that the TLS issue is fixed in Erlang version 21.1.1 (http://erlang.org/download/OTP-21.1.1.README), but the latest release is 21.1.2.

**Version**

We are running `3.7.8-debian-9-r14` and `3.7.8-debian-9-r43` in our environments.

**Comment by carrodher** [comment]
Hi, thanks for the suggestion. We are using the erlang.org releases page (https://www.erlang.org/downloads) to track new releases, but on this page, patch tags are not listed for some reason. We will try to modify our track system in order to detect patches version using GitHub (https://github.com/erlang/otp/releases) instead of erlang.org.

**Comment by carrodher** [comment]
It seems the erlang download page is only tracking minor changes (x.y) but in GitHub, there are patches (x.y.z). We checked that `otp_src_ != OTP-`, so tarballs are not equivalent and we can't replace it in a harmless manner.
