### ISSUE TITLE
CVE vulnerabilities 

### ISSUE THREAD

**Issue by AndreiBamboi** [bitnami/bitnami-docker-rabbitmq#95]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

Scanned rabbitmq:latest and there are 9 HIGH vulnerabilities found.

**Describe the results you received:**

https://security-tracker.debian.org/tracker/CVE-2017-14062
https://security-tracker.debian.org/tracker/CVE-2016-2779
https://security-tracker.debian.org/tracker/CVE-2017-12424
https://security-tracker.debian.org/tracker/CVE-2017-8804
https://security-tracker.debian.org/tracker/CVE-2018-1000001
https://security-tracker.debian.org/tracker/CVE-2018-6485
https://security-tracker.debian.org/tracker/CVE-2018-6551
https://security-tracker.debian.org/tracker/CVE-2019-9169
https://security-tracker.debian.org/tracker/CVE-2019-12900

**Describe the results you expected:**
Most of the vulnerabilities are fixed in debian buster release , as for my own tests with distro-upgrade from strech to buster, revealed only 1 vulnerability left. 
Your team could analyze the if it is possbile to upgrade distro and also check if current vulnerabilities are fixable for current version.
**Version**
rabbitmq:latest (3.7.17-debian-9-r0)

**Comment by rafariossaa** [comment]
Hi @AndreiBamboi,
  First of all, thanks for reporting this.

  This is a common problem of all distros, you have to keep pace with what they a releasing. Some times happen that some fixes are not backported, other times you have bugs in the new distro version but not in the older one, and so on.

  We have daily releases of our images in order to include the upgrades that may appear. If you use rolling tags in your deployments you will have your container images updated.

  Anyway, moving to Debian 10 is our road map.
